SETTINGS = [
    {
        "name": "DRIFT_MODE",
        "values": [
            "MANUAL",
            "AUTO",
        ],
        "default": "MANUAL",
    },
    {
        "name": "SETTING_HUD_LABELS",
        "values": [
            "HIDE",
            "SHOW",
        ],
        "default": "SHOW",
    },
    {
        "name": "SETTING_169_FOV",
        "values": [
            "169",
            "43",
        ],
        "default": "169",
    },
    {
        "name": "SETTING_MAP_ICONS",
        "values": [
            "CHARACTERS",
            "MIIS",
        ],
        "default": "MIIS",
    },
    {
        "name": "TA_RULE_CLASS",
        "values": [
            "150CC",
            "200CC",
        ],
        "default": "150CC",
    },
    {
        "name": "TA_RULE_GHOST_SORTING",
        "values": [
            "FASTEST",
            "SLOWEST",
            "NEWEST",
            "OLDEST",
        ],
        "default": "FASTEST",
    },
    {
        "name": "TA_RULE_GHOST_TAG_VISIBILITY",
        "values": [
            "NONE",
            "WATCHED",
            "ALL",
        ],
        "default": "ALL",
    },
    {
        "name": "TA_RULE_GHOST_TAG_CONTENT",
        "values": [
            "NAME",
            "TIME",
            "TIME_NOLEADING",
            "DATE",
        ],
        "default": "NAME",
    },
    {
        "name": "TA_RULE_SOLID_GHOSTS",
        "values": [
            "NONE",
            "WATCHED",
            "ALL",
        ],
        "default": "NONE",
    },
    {
        "name": "SETTING_PAGE_TRANSITIONS",
        "values": [
            "DISABLE",
            "ENABLE",
        ],
        "default": "ENABLE",
    },
    {
        "name": "SETTING_RACE_INPUT_DISPLAY",
        "values": [
            "DISABLE",
            "SIMPLE",
            "CLASSIC",
            "PRESET2",
            "PRESET3",
            "PRESET4",
            "PRESET5",
            "PRESET6",
        ],
        "default": "SIMPLE",
    },
    {
        "name": "TA_RULE_GHOST_SOUND",
        "values": [
            "NONE",
            "WATCHED",
            "ALL",
        ],
        "default": "WATCHED",
    },
]


def enum_of(setting, v):
    return "SP_" + setting["name"] + "_" + v


def generate_enum(setting):
    body = ""
    for i, v in enumerate(setting["values"]):
        assert v != 'DEFAULT'
        body += f"    {enum_of(setting, v)} = {hex(i)},\n"

    body += f"    {enum_of(setting, 'DEFAULT')} = {enum_of(setting, setting['default'])},\n"
    return "enum {\n" + body + "};\n\n"


def num_bits(setting):
    return (len(setting['values']) - 1).bit_length()


def format_member(setting):
    pascal = setting['name'].title().replace('_', '')

    return pascal[0].lower() + pascal[1:]


def generate_bitfield(setting):
    return f"u32 {format_member(setting)} : {num_bits(setting)};\n"


with open("payload/game/system/SpSetting.h", 'w') as s:
    s.write("// THIS IS AN AUTOGENERATED FILE (settings.py)\n")
    s.write("#pragma once\n\n")

    s.write("#include <Common.h>\n\n")

    s.write("// Enums\n")
    for setting in SETTINGS:
        s.write(generate_enum(setting))
    s.write("\n")

    s.write("// Bit fields\n")
    s.write("typedef struct {\n")
    for setting in SETTINGS:
        s.write("    " + generate_bitfield(setting))
    s.write("} SpSettingBitField;\n")
