#define None -0x1 
#define TARace 0xd 
#define GpPauseMenu 0x17 
#define VsPauseMenu 0x18 
#define TaPauseMenu 0x19 
#define BattlePauseMenu 0x1A 
#define MrPauseMenu 0x1B 
#define TaGhostPauseMenu 0x1C 
#define GhostReplayPauseMenu 0x1F 
#define AfterTaMenu 0x21 
#define AfterVsMenu 0x22 
#define AfterMrMenu 0x25 
#define AfterTournamentMenu 0x26 
#define SendTournamentRecord 0x2A 
#define CheckRankings 0x2B 
#define ConfirmQuit 0x2C 
#define CompetitionPersonalLeaderboard 0x35 
#define GhostReplayRace 0x37 
#define GpReplayPauseMenu 0x38 
#define TaReplayPauseMenu 0x39 
#define OnlinePleaseWait 0x48 
#define RaceConfirm 0x4B 
#define MessagePopup 0x4D 
#define YesNoPopup 0x4E 
#define ReadingGhostData 0x4F 
#define ConnectingNintendoWfc 0x50 
#define MenuMessage 0x51 
#define Confirm 0x52 
#define Title 0x57 
#define TopMenu 0x5A 
#define Model 0x5C 
#define TopOverlay 0x5E 
#define LicenseSelect 0x65 
#define LicenseSettingsTop 0x67 
#define SingleTop 0x69 
#define CharacterSelect 0x6B 
#define VehicleSelect 0x6C 
#define DriftSelect 0x6D 
#define CupSelect 0x6E 
#define CourseSelect 0x6f 
#define TimeAttackTop 0x70 
#define TimeAttackGhostList 0x71 
#define VsModeSelect 0x72 
#define RaceRules 0x73 
#define TeamsOverview 0x74 
#define BattleModeSelect 0x75 
#define BattleVehicleSelect 0x76 
#define BattleRules 0x77 
#define BattleCupSelect 0x78 
#define BattleCourseSelect 0x79 
#define MissionLevelSelect 0x7a 
#define MissionStageSelect 0x7b 
#define MissionPrompt 0x7c 
#define MissionDrift 0x7d 
#define MissionTutorial 0x7e 
#define ServicePackTop 0xa2 // Replaces ChannelTop 
#define StorageBenchmark 0xa3 // Replaces ChannelRanking
#define ServicePackTools 0xa4 // Replaces ChannelGhost
#define GhostManager 0xa7 
#define OptionExplanation 0xc2 
#define OptionSelect2 0xc3 
#define OptionSelect3 0xc4 
#define OptionAwait 0xc7 
#define OptionMessage 0xc8 
#define OptionConfirm 0xc9 
#define Channel 0xca // Replaces ChannelExplanation 
#define Update 0xcb // Replaces ChannelConfirm 
#define Settings 0xce // Replaces LicenseRecordsOverall 
// Disabled { 
#define LicenseRecordsFavorites 0xcf 
#define LicenseRecordsFriends 0xd0 
#define LicenseRecordsWFC 0xd1 
#define LicenseRecordsOther 0xd2 
// } 
#define PageMax 0xd3
