#define Restart 0x5

#define GP 0x1e
#define TA 0x1f

#define VS1P 0x20
#define VS2P 0x21
#define VS3P 0x22
#define VS4P 0x23

#define TeamVS1P 0x24
#define TeamVS2P 0x25
#define TeamVS3P 0x26
#define TeamVS4P 0x27

#define Battle1P 0x28
#define Battle2P 0x29
#define Battle3P 0x2a
#define Battle4P 0x2b

#define MR 0x2c

#define TournamentReplay 0x2d
#define GPReplay 0x2e
#define TAReplay 0x2f

#define GhostTA 0x30
#define GhostTAOnline 0x31

#define GhostReplayChannel 0x32
#define GhostReplayDownload 0x33
#define GhostReplay 0x34

#define TitleFromMenu 0x41
#define TitleFromOptions 0x43
#define MiiSelectCreate 0x45
#define MiiSelectChange 0x46
#define LicenseSettings 0x47

#define Single 0x48
#define SingleChangeDriver 0x49
#define SingleChangeCourse 0x4a
#define SingleChangeMission 0x4d

#define SingleChangeGhostData 0x4e // Replaces SingleMkChannelGhost
#define SingleLeaderboardGhost 0x4f

#define OnlineSingle 0x55 // Replaces WifiSingle
#define OnlineMultiConfigure 0x5a // Replaces WifiMultiConfigure
#define OnlineMulti 0x5b // Replaces WifiMulti

#define ServicePack 0x7a // Replaces Channel

#define OnlineServer 0x84 // Replaces FriendListFromChannel

#define Unlock0 0x90
#define Unlock1 0x91
#define Unlock2 0x92
#define Unlock3 0x93

#define SectionMax 0x95
